#!/usr/bin/env bash
set -euo pipefail

require_env() {
  local name="$1"
  if [[ -z "${!name:-}" ]]; then
    echo "Missing required environment variable: ${name}" >&2
    exit 1
  fi
}

decode_base64_to_file() {
  local value="$1"
  local target="$2"
  python3 - "$value" "$target" <<'PY'
import base64
import pathlib
import sys

value, target = sys.argv[1], pathlib.Path(sys.argv[2])
target.parent.mkdir(parents=True, exist_ok=True)
target.write_bytes(base64.b64decode(value))
PY
}

require_env FIREBASE_OPTIONS_DART_BASE64
require_env GOOGLE_SERVICE_INFO_PLIST_BASE64
require_env GOOGLE_SERVICES_JSON_BASE64
require_env GOOGLE_REVERSED_CLIENT_ID

decode_base64_to_file "$FIREBASE_OPTIONS_DART_BASE64" lib/firebase_options.dart
decode_base64_to_file \
  "$GOOGLE_SERVICE_INFO_PLIST_BASE64" \
  ios/Runner/GoogleService-Info.plist
decode_base64_to_file \
  "$GOOGLE_SERVICES_JSON_BASE64" \
  android/app/google-services.json

mkdir -p ios/Flutter
{
  echo "// Generated by scripts/ci/restore_firebase_config.sh"
  echo "GOOGLE_REVERSED_CLIENT_ID=${GOOGLE_REVERSED_CLIENT_ID}"
} > ios/Flutter/Firebase.local.xcconfig

echo "Firebase client configuration restored for iOS and Android CI."
