// Mocks generated by Mockito 5.4.6 from annotations
// in time_boxing_pomodoro/test/features/calendar/data/repositories/calendar_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:time_boxing_pomodoro/features/calendar/data/datasources/apple_calendar_platform_channel.dart'
    as _i5;
import 'package:time_boxing_pomodoro/features/calendar/data/datasources/calendar_app_platform_channel.dart'
    as _i8;
import 'package:time_boxing_pomodoro/features/calendar/data/datasources/calendar_mapping_local_datasource.dart'
    as _i7;
import 'package:time_boxing_pomodoro/features/calendar/data/datasources/google_calendar_datasource.dart'
    as _i3;
import 'package:time_boxing_pomodoro/features/calendar/data/dtos/calendar_export_dto.dart'
    as _i2;
import 'package:time_boxing_pomodoro/features/calendar/domain/entities/calendar_export.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCalendarExportResultDto_0 extends _i1.SmartFake
    implements _i2.CalendarExportResultDto {
  _FakeCalendarExportResultDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoogleCalendarRestClient_1 extends _i1.SmartFake
    implements _i3.GoogleCalendarRestClient {
  _FakeGoogleCalendarRestClient_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCalendarAppOpenResult_2 extends _i1.SmartFake
    implements _i4.CalendarAppOpenResult {
  _FakeCalendarAppOpenResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppleCalendarPlatformChannel].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppleCalendarPlatformChannel extends _i1.Mock
    implements _i5.AppleCalendarPlatformChannel {
  @override
  _i6.Future<_i2.CalendarExportResultDto> exportEvents(
    _i4.CalendarExportRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#exportEvents, [request]),
            returnValue: _i6.Future<_i2.CalendarExportResultDto>.value(
              _FakeCalendarExportResultDto_0(
                this,
                Invocation.method(#exportEvents, [request]),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i2.CalendarExportResultDto>.value(
                  _FakeCalendarExportResultDto_0(
                    this,
                    Invocation.method(#exportEvents, [request]),
                  ),
                ),
          )
          as _i6.Future<_i2.CalendarExportResultDto>);
}

/// A class which mocks [GoogleCalendarDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleCalendarDataSource extends _i1.Mock
    implements _i3.GoogleCalendarDataSource {
  @override
  _i3.GoogleCalendarRestClient get restClient =>
      (super.noSuchMethod(
            Invocation.getter(#restClient),
            returnValue: _FakeGoogleCalendarRestClient_1(
              this,
              Invocation.getter(#restClient),
            ),
            returnValueForMissingStub: _FakeGoogleCalendarRestClient_1(
              this,
              Invocation.getter(#restClient),
            ),
          )
          as _i3.GoogleCalendarRestClient);

  @override
  _i6.Future<_i2.CalendarExportResultDto> exportEvents(
    _i4.CalendarExportRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#exportEvents, [request]),
            returnValue: _i6.Future<_i2.CalendarExportResultDto>.value(
              _FakeCalendarExportResultDto_0(
                this,
                Invocation.method(#exportEvents, [request]),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i2.CalendarExportResultDto>.value(
                  _FakeCalendarExportResultDto_0(
                    this,
                    Invocation.method(#exportEvents, [request]),
                  ),
                ),
          )
          as _i6.Future<_i2.CalendarExportResultDto>);
}

/// A class which mocks [CalendarMappingLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalendarMappingLocalDataSource extends _i1.Mock
    implements _i7.CalendarMappingLocalDataSource {
  @override
  _i6.Future<void> saveMappings(
    String? provider,
    String? dateKey,
    List<_i2.CalendarEventMappingDto>? mappings,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveMappings, [provider, dateKey, mappings]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i2.CalendarEventMappingDto>> loadMappings(
    String? provider,
    String? dateKey,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#loadMappings, [provider, dateKey]),
            returnValue: _i6.Future<List<_i2.CalendarEventMappingDto>>.value(
              <_i2.CalendarEventMappingDto>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<_i2.CalendarEventMappingDto>>.value(
                  <_i2.CalendarEventMappingDto>[],
                ),
          )
          as _i6.Future<List<_i2.CalendarEventMappingDto>>);
}

/// A class which mocks [CalendarAppPlatformChannel].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalendarAppPlatformChannel extends _i1.Mock
    implements _i8.CalendarAppPlatformChannel {
  @override
  _i6.Future<_i4.CalendarAppOpenResult> open(_i4.CalendarProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#open, [provider]),
            returnValue: _i6.Future<_i4.CalendarAppOpenResult>.value(
              _FakeCalendarAppOpenResult_2(
                this,
                Invocation.method(#open, [provider]),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i4.CalendarAppOpenResult>.value(
                  _FakeCalendarAppOpenResult_2(
                    this,
                    Invocation.method(#open, [provider]),
                  ),
                ),
          )
          as _i6.Future<_i4.CalendarAppOpenResult>);
}
