app_identifier(ENV.fetch("APP_IDENTIFIER", "com.seongwoo.focusmark"))
username(ENV["APPLE_ID"]) if ENV["APPLE_ID"].to_s.length.positive?

metadata_path("./metadata")
screenshots_path("./screenshots")

submit_for_review(false)
automatic_release(false)
force(true)
skip_screenshots(true)
skip_metadata(false)
run_precheck_before_submit(true)

privacy_url("https://timebox-mark-prod.web.app/privacy/")
support_url("https://timebox-mark-prod.web.app/support/")
marketing_url("https://timebox-mark-prod.web.app/")
