app_identifier(ENV.fetch("APP_IDENTIFIER", "com.seongwoo.focusmark"))
username(ENV["APPLE_ID"]) if ENV["APPLE_ID"].to_s.length.positive?

metadata_path("./metadata")
screenshots_path("./screenshots")

submit_for_review(false)
automatic_release(false)
force(true)
skip_screenshots(false)
skip_metadata(false)
run_precheck_before_submit(true)
precheck_include_in_app_purchases(false)
